---
- name: Deploying STARK Default Domain Policy in stark-industries.midgard.mrvl
  community.vmware.vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    vm_id: "{{ vm }}"
    vm_username: "{{ win_domain_admin }}"
    vm_password: "{{ win_admin_password }}"
    vm_shell: 'C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
    # vm_shell_args: '-ExecutionPolicy Bypass -Command { {{ config }} }'
    vm_shell_args: |
      C:\Users\Administrator\Desktop\STARK_Default_Domain_Policy.ps1
    wait_for_process: false
  ignore_errors: false

- name: Rebooting Domain Controller stk-dc-01.stark-industries.midgard.mrvl
  community.vmware.vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    vm_id: "{{ vm }}"
    vm_username: "{{ win_domain_admin }}"
    vm_password: "{{ win_admin_password }}"
    vm_shell: 'C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
    # vm_shell_args: '-ExecutionPolicy Bypass -Command { {{ config }} }'
    vm_shell_args: |
      Restart-Computer -Force
    wait_for_process: false
  ignore_errors: false