---
- name: Initialize Terraform Environment
  import_tasks: ../common/tasks/terraform_init.yml    # 'terraform init''
  vars:
    terraform_folder_var: "{{ terraform_root }}/vm"

- name: Apply Terraform Configuration
  import_tasks: ../common/tasks/terraform_apply_module.yml    # 'terraform apply''
  vars:
    module: "SDP"
    terraform_folder_var: "{{ terraform_root }}/vm"
    task_title: "Deploying OBSIDIAN DAGGER Border Routers"