---
- name: "Applying {{ vm }} server configuration"
  community.vmware.vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    vm_id: "{{ vm }}"
    vm_username: "{{ win_admin }}"
    vm_password: "{{ win_admin_password }}"
    vm_shell: 'C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
    vm_shell_args: |
      Disable-NetAdapterBinding -Name 'Ethernet0' -ComponentID 'ms_tcpip6'
      cscript.exe C:\Windows\System32\slmgr.vbs /skms kms.activation.sls.microsoft.com
      cscript.exe C:\Windows\System32\slmgr.vbs /ato
      Set-DnsClientServerAddress -InterfaceAlias 'Ethernet0' -ServerAddresses ('4.78.128.20')
      Set-TimeZone -Id 'Eastern Standard Time'
      Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\ServerManager\\Roles\\12' -Name ConfigurationState -Value 2
      Set-ItemProperty -Path 'HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce' -Name '!Configure_AD' -Value 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -noexit -File C:\Users\Administrator\Desktop\STARK_AD_Config.ps1'
    wait_for_process: true
  ignore_errors: false