---
- name: "Configuring WinRM on {{ vm }}"
  community.vmware.vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    vm_id: "{{ vm }}"
    vm_username: "{{ win_admin }}"
    vm_password: "{{ win_admin_password }}"
    vm_shell: 'C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe'
    vm_shell_args: |
      $certificateThumbprint = (New-SelfSignedCertificate -DnsName 'stk-dc-01' -CertStoreLocation Cert:\LocalMachine\My).Thumbprint; create winrm/config/Listener?Address=*+Transport=HTTPS '@{Hostname="stk-dc-01"; CertificateThumbprint="${certificateThumbprint}"}'
      Restart-Service WinRM
    wait_for_process: false