Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\NetLogon\Parameters" -Name "NegativeCachePeriod" -Value 0 -Type DWord
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters" -Name "MaxNegativeCacheTtl" -Value 0 -Type DWord
Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters" -Name "AlwaysExpectDomainController" -Value 1 -Type DWord
Set-DnsClientServerAddress -InterfaceAlias 'Ethernet0' -ServerAddresses ('4.78.128.20')
Add-DnsServerPrimaryZone -NetworkID 4.78.128.0/21 -ZoneFile 128.78.4.in-addr.arpa.dns
Add-DnsServerForwarder -IPAddress 46.244.164.88 -PassThru
Add-DnsServerResourceRecordPtr -Name "20" -ZoneName "128.78.4.in-addr.arpa" -AllowUpdateAny -TimeToLive 01:00:00 -AgeRecord -PtrDomainName "stk-dc-01.stark-industries.midgard.mrvl"
Rename-ADObject -Identity "CN=Default-First-Site-Name,CN=Sites,CN=Configuration,DC=stark-industries,DC=midgard,DC=mrvl" -NewName "Stark-HQ"
New-ADReplicationSite -Name "Stark-OL-A"
New-ADReplicationSite -Name "Stark-OL-B"
New-ADReplicationSite -Name "Stark-OL-C"
New-ADReplicationSubnet -Name "4.78.128.0/23" -Site "Stark-HQ"
New-ADReplicationSubnet -Name "4.78.130.0/23" -Site "Stark-OL-A"
New-ADReplicationSubnet -Name "4.78.132.0/23" -Site "Stark-OL-B"
New-ADReplicationSubnet -Name "4.78.134.0/23" -Site "Stark-OL-C"
New-ADOrganizationalUnit -Name "STARK" -Path "DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Servers" -Path "OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Departments" -Path "OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Development" -Path "OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Human Resources" -Path "OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Operations" -Path "OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Research" -Path "OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Workstations" -Path "OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Linux Workstations" -Path "OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Windows Workstations" -Path "OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Users" -Path "OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Groups" -Path "OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Workstations" -Path "OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Linux Workstations" -Path "OU=Workstations,OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Windows Workstations" -Path "OU=Workstations,OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Users" -Path "OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Groups" -Path "OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Workstations" -Path "OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Linux Workstations" -Path "OU=Workstations,OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Windows Workstations" -Path "OU=Workstations,OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Users" -Path "OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Groups" -Path "OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Workstations" -Path "OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Linux Workstations" -Path "OU=Workstations,OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Windows Workstations" -Path "OU=Workstations,OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Users" -Path "OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Groups" -Path "OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-ex-01" -SamAccountName "stk-ex-01" -Path "OU=Servers,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-as-01" -SamAccountName "stk-as-01" -Path "OU=Servers,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-lhm-01" -SamAccountName "stk-lhm-01" -Path "OU=Servers,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-fhm-01" -SamAccountName "stk-fhm-01" -Path "OU=Servers,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-hst-01" -SamAccountName "stk-hst-01" -Path "OU=Servers,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-rsch-a29e5p" -SamAccountName "stk-rsch-a29e5p" -Path "OU=Windows Workstations,OU=Workstations,OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-rsch-62c271" -SamAccountName "stk-rsch-62c271" -Path "OU=Windows Workstations,OU=Workstations,OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-rsch-a87ffb" -SamAccountName "stk-rsch-a87ffb" -Path "OU=Windows Workstations,OU=Workstations,OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-rsch-6604ec" -SamAccountName "stk-rsch-6604ec" -Path "OU=Windows Workstations,OU=Workstations,OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-rsch-0aec35" -SamAccountName "stk-rsch-0aec35" -Path "OU=Windows Workstations,OU=Workstations,OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-rsch-28eddc" -SamAccountName "stk-rsch-28eddc" -Path "OU=Windows Workstations,OU=Workstations,OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-rsch-bc4dfe" -SamAccountName "stk-rsch-bc4dfe" -Path "OU=Linux Workstations,OU=Workstations,OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-0f7d34" -SamAccountName "stk-dev-0f7d34" -Path "OU=Windows Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-99ba3e" -SamAccountName "stk-dev-99ba3e" -Path "OU=Windows Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-816dce" -SamAccountName "stk-dev-816dce" -Path "OU=Windows Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-bbae60" -SamAccountName "stk-dev-bbae60" -Path "OU=Windows Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-ac4834" -SamAccountName "stk-dev-ac4834" -Path "OU=Windows Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-ad26de" -SamAccountName "stk-dev-ad26de" -Path "OU=Linux Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-a27e28" -SamAccountName "stk-dev-a27e28" -Path "OU=Linux Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-77ffea" -SamAccountName "stk-dev-77ffea" -Path "OU=Linux Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-17dce4" -SamAccountName "stk-dev-17dce4" -Path "OU=Linux Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-29afec" -SamAccountName "stk-dev-29afec" -Path "OU=Linux Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-28eeca" -SamAccountName "stk-dev-28eeca" -Path "OU=Linux Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-0385dd" -SamAccountName "stk-dev-0385dd" -Path "OU=Linux Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-34fcea" -SamAccountName "stk-dev-34fcea" -Path "OU=Linux Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-e37ace" -SamAccountName "stk-dev-e37ace" -Path "OU=Linux Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-dev-eee5ac" -SamAccountName "stk-dev-eee5ac" -Path "OU=Linux Workstations,OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-ops-7cb6b9" -SamAccountName "stk-ops-7cb6b9" -Path "OU=Windows Workstations,OU=Workstations,OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-ops-26eacf" -SamAccountName "stk-ops-26eacf" -Path "OU=Windows Workstations,OU=Workstations,OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-ops-173eeb" -SamAccountName "stk-ops-173eeb" -Path "OU=Windows Workstations,OU=Workstations,OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-ops-100caa" -SamAccountName "stk-ops-100caa" -Path "OU=Windows Workstations,OU=Workstations,OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-ops-547002" -SamAccountName "stk-ops-547002" -Path "OU=Windows Workstations,OU=Workstations,OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-ops-bb6587" -SamAccountName "stk-ops-bb6587" -Path "OU=Windows Workstations,OU=Workstations,OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-ops-26db55" -SamAccountName "stk-ops-26db55" -Path "OU=Linux Workstations,OU=Workstations,OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-ops-5ae36b" -SamAccountName "stk-ops-5ae36b" -Path "OU=Linux Workstations,OU=Workstations,OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-hr-950abe" -SamAccountName "stk-hr-950abe" -Path "OU=Windows Workstations,OU=Workstations,OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-hr-264b4e" -SamAccountName "stk-hr-264b4e" -Path "OU=Windows Workstations,OU=Workstations,OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-hr-29bcec" -SamAccountName "stk-hr-29bcec" -Path "OU=Windows Workstations,OU=Workstations,OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-hr-cc8317" -SamAccountName "stk-hr-cc8317" -Path "OU=Windows Workstations,OU=Workstations,OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-hr-93bace" -SamAccountName "stk-hr-93bace" -Path "OU=Windows Workstations,OU=Workstations,OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-hr-ac3476" -SamAccountName "stk-hr-ac3476" -Path "OU=Windows Workstations,OU=Workstations,OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-hr-819fed" -SamAccountName "stk-hr-819fed" -Path "OU=Windows Workstations,OU=Workstations,OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"