New-ADComputer -Name "stk-ex-01" -SamAccountName "stk-ex-01" -Path "OU=Servers,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-as-01" -SamAccountName "stk-as-01" -Path "OU=Servers,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-lhm-01" -SamAccountName "stk-lhm-01" -Path "OU=Servers,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-fhm-01" -SamAccountName "stk-fhm-01" -Path "OU=Servers,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADComputer -Name "stk-hst-01" -SamAccountName "stk-hst-01" -Path "OU=Servers,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"