New-ADOrganizationalUnit -Name "STARK" -Path "DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Servers" -Path "OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Departments" -Path "OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Development" -Path "OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Human Resources" -Path "OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Operations" -Path "OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Research" -Path "OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Workstations" -Path "OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Linux Workstations" -Path "OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Windows Workstations" -Path "OU=Workstations,OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Users" -Path "OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Groups" -Path "OU=Development,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Workstations" -Path "OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Linux Workstations" -Path "OU=Workstations,OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Windows Workstations" -Path "OU=Workstations,OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Users" -Path "OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Groups" -Path "OU=Human Resources,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Workstations" -Path "OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Linux Workstations" -Path "OU=Workstations,OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Windows Workstations" -Path "OU=Workstations,OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Users" -Path "OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Groups" -Path "OU=Operations,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Workstations" -Path "OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Linux Workstations" -Path "OU=Workstations,OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Windows Workstations" -Path "OU=Workstations,OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Users" -Path "OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"
New-ADOrganizationalUnit -Name "Groups" -Path "OU=Research,OU=Departments,OU=STARK,DC=stark-industries,DC=midgard,DC=mrvl"