---
- name: "{{ task_title }}"
  ansible.builtin.command: terraform apply -target=module.{{ module }} --auto-approve -var-file=sensitive.tfvars
  become: no
  args:
    chdir: "{{ terraform_folder_var }}"