---
# - name: Wait for {{ vm }} to be available
#   community.vmware.vmware_guest_tools_wait:
#     hostname: "{{ vcenter_hostname }}"
#     username: "{{ vcenter_username }}"
#     password: "{{ vcenter_password }}"
#     validate_certs: "{{ vcenter_validate_certs }}"
#     datacenter: "{{ vcenter_datacenter }}"
#     name: "{{ vm }}"
#     timeout: 120
#   delegate_to: localhost

- name: Wait for {{ vm }} to be available...
  community.vmware.vmware_guest_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ vm }}"
  delegate_to: localhost
  register: vm_info
  until: vm_info.instance.guest_tools_status == "guestToolsRunning"
  retries: 60
  delay: 5