---
- name: Gather All Windows Client VMs
  community.vmware.vmware_vm_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    folder: "/CDX Datacenter/vm/CDX Environment/OBSIDIAN DAGGER/Blue Team/Clients"
  register: client_list

- name: Filter VMs with Windows guests
  set_fact:
    windows_clients: "{{ client_list.virtual_machines | selectattr('guest_fullname', 'match', '.*Microsoft Windows.*', 'i') | map(attribute='guest_name') | list }}"

- name: Gather All Windows Server VMs
  community.vmware.vmware_vm_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    folder: "/CDX Datacenter/vm/CDX Environment/OBSIDIAN DAGGER/Blue Team/Member Servers"
  register: server_list

- name: Filter VMs with Windows guests
  set_fact:
    windows_servers: "{{ server_list.virtual_machines | selectattr('guest_fullname', 'match', '.*Microsoft Windows.*', 'i') | map(attribute='guest_name') | list }}"

- name: Concatenate lists
  set_fact:
    windows_systems: "{{ windows_clients + windows_servers }}"

- name: Activate Windows OS
  import_tasks: ../../common/tasks/win_activate_windows.yml
  vars:
    windows_vms: "{{ windows_systems }}"